module.exports = {
  practoPageURL: "https://www.practo.com/medicine-info",
  drugsUpdatePageURL: "http://www.drugsupdate.com/",
  mimsPageURL: "https://www.mims.com/india",
  informedHealthPageURL: "https://www.informedhealth.org/",
  mayoClinicalPageURL: "https://www.mayoclinic.org/diseases-conditions",
  wikipediaPageURL: "https://www.wikipedia.org/",
  mimsOrderedHeadings: [
    "Dosage/Direction for Use",
    "Administration",
    "Adverse Reactions",
    "Special Precautions",
    "Contraindications",
    "Drug Interactions",
    "Overdosage",
    "Storage",
    "Action",
  ],
  drugTypeMapping: {
    vial: "Vial",
    cap: "Capsule",
    inj: "Injection",
    susp: "Suspension",
    dps: "Drops",
    pwd: "Powder",
    oint: "Ointment",
    soln: "Solution",
    crm: "Cream",
    liqd: "Liquid",
    // tab: "Tablet",
    // syr: "Syrup",
    // syrup: "Syrup"
    // "dry-syr": "Syrup",
  },
};
